export const paths = {
  PROVIDER_LOGO: require('../assets/Icons_Images/png/providers.png'),
  PATIENTS_LOGO: require('../assets/Icons_Images/png/patients.png'),
  STAFF_LOGO: require('../assets/Icons_Images/png/staff.png'),
  PROVIDER_TYPES: {
    SNF_ALF: require('../assets/Icons_Images/png/snf_alf.png'),
    HMO: require('../assets/Icons_Images/png/hmo.png'),
    MEDICAL_OP_CENTERS: require('../assets/Icons_Images/png/medical-center.png'),
    WORKERS: require('../assets/Icons_Images/png/workers.png'),
  },
  WELCOME_BG: require('../assets/Icons_Images/png/bg.png'),
  COMMON_BG: require('../assets/Icons_Images/png/round.png'),
  LOGO: require('../assets/Icons_Images/png/app-logo.png'),
  TRANPARENT_LOGO: require('../assets/Icons_Images/png/transparent_logo.png'),
  MOBILITY_CLINIC: require('../assets/Icons_Images/png/mobility_clinic.png'),
  IDEAL_HEALTHCARE: require('../assets/Icons_Images/png/ideal_healthcare.png'),
  REHAB_SVCS: require('../assets/Icons_Images/png/mobility_rehab.png'),
  GREEN_PROSTHETICS: require('../assets/Icons_Images/png/green_prosthetics.png'),
  CARE_CRAFTERS: require('../assets/Icons_Images/png/care_crafters.png'),
};

export const FORM_ICONS = {
  avatar_placeholder: require('../assets/Icons_Images/png/patient_added3x.png'),
  email: require('../assets/Icons_Images/png/Mail.png'),
  passwrord_lock: require('../assets/Icons_Images/png/Lock.png'),
  passwrord_eye_open: require('../assets/Icons_Images/png/view_detail.png'),
  passwrord_eye_closed: require('../assets/Icons_Images/png/hiddens.png'),
  address: require('../assets/Icons_Images/png/address.png'),
  city: require('../assets/Icons_Images/png/address.png'),
  state: require('../assets/Icons_Images/png/address.png'),
  postcode: require('../assets/Icons_Images/png/address.png'),
  country: require('../assets/Icons_Images/png/address.png'),
  birthday: require('../assets/Icons_Images/png/birthday.png'),
  calendar: require('../assets/Icons_Images/png/calendar.png'),
  gender: require('../assets/Icons_Images/png/gender.png'),
  mobile: require('../assets/Icons_Images/png/Mobile.png'),
  check: require('../assets/Icons_Images/png/thanks_check.png'),
  firstname: require('../assets/Icons_Images/png/firstname.png'),
  company_name: require('../assets/Icons_Images/png/company_name.png'),
};
